export const USER_LOADING='USER_LOADING';
export const USER_GET_DATA='USER_GET_DATA';
export const USER_END_LOADING='USER_END_LOADING';
export const USER_FAILURE='USER_FAILURE';
export const CLEAR_USER='CLEAR_USER';
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
