export const USER_LOADING='USER_LOADING';
export const USER_GET_DATA='USER_GET_DATA';
export const USER_END_LOADING='USER_END_LOADING';
export const USER_FAILURE='USER_FAILURE';
export const CLEAR_USER='CLEAR_USER';
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";


export const HOTELS_LOADING='HOTELS_LOADING';
export const HOTELS_GET_DATA='HOTELS_GET_DATA';
export const HOTELS_END_LOADING='HOTELS_END_LOADING';
export const HOTELS_FAILURE='HOTELS_FAILURE';
export const CLEAR_HOTELS='CLEAR_HOTELS';


export const INDEX_LOADING='INDEX_LOADING'
export const INDEX_GET_DATA='INDEX_GET_DATA';
export const INDEX_GET_CHILDDATA='INDEX_GET_CHILDDATA';
export const INDEX_GET_ENFANTDATA='INDEX_GET_ENFANTDATA';
export const INDEX_GET_ADULTDATA='INDEX_GET_ADULTDATA';
export const INDEX_GET_AGESDATA='INDEX_GET_AGESDATA';
export const INDEX_GET_ROOMDATA='INDEX_GET_ROOMDATA';
export const INDEX_END_LOADING='INDEX_END_LOADING';
export const INDEX_FAILURE='INDEX_FAILURE';
export const CLEAR_INDEX='CLEAR_INDEX';

export const AVAILABLEROOMS_LOADING='AVAILABLEROOMS_LOADING';
export const AVAILABLEROOMS_GET_DATA='AVAILABLEROOMS_GET_DATA';
export const AVAILABLEROOMS_END_LOADING='AVAILABLEROOMS_END_LOADING';
export const AVAILABLEROOMS_FAILURE='AVAILABLEROOMS_FAILURE';
export const AVAILABLEROOMS_CLEAR='AVAILABLEROOMS_CLEAR';

export const CURRENTDATA_LOADING='CURRENTDATA_LOADING';
export const CURRENTDATA_GET_HOTEL='CURRENTDATA_GET_HOTEL';
export const CURRENTDATA_GET_DATA='CURRENTDATA_GET_DATA';
export const CURRENTDATA_GET_ROOMS='CURRENTDATA_GET_ROOMS';
export const CURRENTDATA_END_LOADING='CURRENTDATA_END_LOADING';
export const CURRENTDATA_FAILURE='CURRENTDATA_FAILURE';
export const CURRENTDATA_CLEAR='CURRENTDATA_CLEAR';

export const CITY_LOADING='CITY_LOADING';
export const CITY_GET_DATA='CITY_GET_DATA';
export const CITY_END_LOADING='CITY_END_LOADING';
export const CITY_FAILURE='CITY_FAILURE';
export const CITY_CLEAR='CITY_CLEAR';

export const RESERVATION_LOADING='RESERVATION_LOADING';
export const RESERVATION_GET_DATA='RESERVATION_GET_DATA';
export const RESERVATION_END_LOADING='RESERVATION_END_LOADING';
export const RESERVATION_FAILURE='RESERVATION_FAILURE';
export const RESERVATION_CLEAR='RESERVATION_CLEAR';